test_mode: true

servo_config:
  n_servos: 3
  origin: [0, 0, 0]
  ceiling: [180, 180, 180]
  total_positions: 200

dataset:
  n_eeg_channels: 5
  training_samples: 1000
  inference_samples_per_position: 1
  eeg_mean: 0.0
  eeg_std: 1.0