services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6380:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - default

  redis-channel-monitor:
    build:
      context: ./services/monitoring
      dockerfile: Dockerfile
    container_name: redis-channel-monitor
    ports:
      - "8082:8082"
    environment:
      - REDIS_URL=redis://redis:6379
      - PROMETHEUS_PORT=8082
    depends_on:
      - redis
    networks:
      - default
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./services/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./services/monitoring/prometheus/alert_rules.yml:/etc/prometheus/alert_rules.yml
      - ../../shared/prometheus_data:/prometheus_data
    ports:
      - "9090:9090"
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - redis-channel-monitor
  
  grafana:
    image: grafana/grafana
    container_name: grafana
    volumes:
      - ./services/monitoring/grafana/datasources/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./services/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_JSON_ENABLED=true
    depends_on:
      - prometheus

volumes:
  redis_data:

networks:
  default:
    driver: bridge