version: "3.8"

services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mechanicus-network

  data-collector:
    build: ./services/data-collector
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mechanicus-network
    command:
      ["python", "data_collection.py", "--redis-url", "redis://redis:6379", "--quiet"]

  eeg-processor:
    build: ./services/eeg-processor
    depends_on:
      - redis
      - data-collector
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mechanicus-network
    command:
      ["python", "utils/preprocessing.py"]

networks:
  mechanicus-network:
    driver: bridge
