name: mechanicus-prod

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - mechanicus-network

  data-collector:
    build: 
      context: ./services/data-collector
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./shared/config:/app/shared/config:ro
    command: ["python", "data_collection.py", "--config", "/app/shared/config/mechanicus_run_configuration.yaml", "--quiet"]
    networks:
      - mechanicus-network

  eeg-processor:
    build: ./services/eeg-processor
    depends_on:
      - redis
      - data-collector
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mechanicus-network
    command: ["python", "utils/preprocessing.py"]

  inference-model:
    build: ./services/eeg-processor
    depends_on:
      - redis
      - eeg-processor
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./shared/models:/app/shared/models:ro
    networks:
      - mechanicus-network
    command: ["python", "models/inference_model.py"]

  rl-agent:
    build:
      context: ./services/servo-controller
      dockerfile: Dockerfile
    command: ["python", "rl_agent/agent.py"]
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mechanicus-network
    volumes:
      - ./shared/models:/app/shared/models:ro
    restart: unless-stopped

  servo-driver:
    build:
      context: ./services/servo-controller
      dockerfile: Dockerfile
    command: ["python", "controllers/servo_driver.py", "-t"]
    depends_on:
      - redis
      - rl-agent
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mechanicus-network
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"  # Adjust based on your servo hardware
    privileged: true  # May be needed for hardware access
    restart: unless-stopped

networks:
  mechanicus-network:
    driver: bridge

volumes:
  redis_data: