version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - mechanicus-network

  data-collector:
    build: 
      context: ./services/data-collector
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./shared/config:/app/shared/config:ro
    command: ["python", "data_collection.py", "--config", "/app/shared/config/mechanicus_run_configuration.yaml"]
    networks:
      - mechanicus-network

  eeg-processor:
    build: ./services/eeg-processor
    depends_on:
      - redis
      - data-collector
    environment:
      - REDIS_URL=redis://redis:6379
    networks:
      - mechanicus-network
    command: ["python", "utils/preprocessing.py"]

networks:
  mechanicus-network:
    driver: bridge

volumes:
  redis_data: