global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'mechanicus-redis-channels'
    static_configs:
      - targets: ['redis-channel-monitor:8082']
    scrape_interval: 5s
    metrics_path: '/metrics'